openapi: 3.0.0
info:
  title: Common Api
  version: 1.0.0
  description: Common Api

servers:
  - url: http://localhost:8080
    description: Local server

paths:

components:
  parameters:
    pageParam:
      name: page
      in: query
      description: Page number of the requested page
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    sizeParam:
        name: size
        in: query
        description: Size of the requested page
        required: false
        schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
    sortParam:
        name: sort
        in: query
        description: "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported."
        required: false
        schema:
          type: array
          items:
            type: string
  schemas:
    PaginationResponse:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          default: 0
        totalPages:
          type: integer
          default: 0
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        numberOfElements:
          type: integer
        size:
          type: integer
        empty:
          type: boolean
      required:
        - totalElements
        - totalPages
        - first
        - last
        - number
        - numberOfElements
        - size
        - empty

    Sort:
      type: object
      format: sort
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
      required:
        - sorted
        - unsorted
        - empty