openapi: 3.0.0
info:
  title: "Template Message Api"
  version: 1.0.0
  description: "Template Message Api"

servers:
  - url: http://localhost:8080
    description: "Local server"

paths:
  /messages:
    get:
      tags:
        - messages
      summary: "Get all messages"
      operationId: getAllMessages
      x-spring-paginated: true
      parameters:
        - $ref: 'Common.yaml#/components/parameters/pageParam'
        - $ref: 'Common.yaml#/components/parameters/sizeParam'
        - $ref: 'Common.yaml#/components/parameters/sortParam'
      responses:
        200:
          description: "A list of messages"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMessageResponse'
    post:
      tags:
          - messages
      summary: "Create a new message"
      operationId: createMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreateRequest'
      responses:
        200:
          description: "The created message"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

components:
  schemas:
    PaginatedMessageResponse:
      type: object
      allOf:
        - $ref: 'Common.yaml#/components/schemas/PaginationResponse'
        - properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/MessageResponse'

    MessageCreateRequest:
      type: object
      properties:
        text:
          type: string
          format: text
          minLength: 5
          maxLength: 10
      required:
        - text

    MessageResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/MessageCreateRequest'
        - properties:
            id:
              type: integer
              format: int64